##trigger: none
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'

pr: 
  branches:
    include:
      - '*'
pool:
  name: 'SonarQube Integration Agent Pool'

variables:
  - template: variables/application-variables.yml
  - template: variables/acr-variables.yml
  - template: variables/aks-variables.yml
  - template: variables/sonarQube-variables.yml


stages:
 - template: stages/cen_dotnet_PR_stage.yml  #Include the stage-level template
   parameters:
     stageName: 'PRValidation' # Specify the stage name
     condition: eq(variables['Build.Reason'], 'PullRequest')
   
 - template: stages/cen_dotnet_CI_stage.yml  # Include the stage-level templat
   parameters:
     stageName: 'CI'  # Specify the stage name
     condition: ne(variables['Build.Reason'], 'PullRequest')

 - template: stages/cen_dotnet_CD_stage.yml  # Include the stage-level template
   parameters:
     stageName: 'CD'  # Specify the stage name
     condition: and(eq(dependencies.PRValidation.result, 'Skipped'), eq(dependencies.CI.result, 'Succeeded'), ne(variables['Build.Reason'], 'PullRequest'))
     dependsOn:
       - PRValidation
       - CI
 
