apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkc29jb250YWluZXJyZWdpc3RyeS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoibXlUb2tlbiIsInBhc3N3b3JkIjoiNXdYdEZRdmk4TFNBb3BlMWhIZFBSSXBSSjFBemNmMXNMRUkwSFV5Y1RCK0FDUkNZQjZjZCIsImF1dGgiOiJiWGxVYjJ0bGJqbzFkMWgwUmxGMmFUaE1VMEZ2Y0dVeGFFaGtVRkpKY0ZKS01VRjZZMll4YzB4RlNUQklWWGxqVkVJclFVTlNRMWxDTm1OayJ9fX0=
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-config
data:
  K8S_CLUSTER: K8S_Agent # AKS Cluster Name
  SUBSCRIPTION_SC: DXO_Service_Connection #Service Connection to the Subscription containing the AKS
  ACR_SC: Docker-ADO connection # Service Connection to the ACR

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet-container
          image: dsocontainerregistry.azurecr.io/dotnet:latest 
          ports:
            - containerPort: 8080 
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"                
          env :
            - name: ENV 
              value: "PROD"
      imagePullSecrets:
        - name: acr-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080












































